### ISSUE TITLE
Getting Started with Pass Frameworks

### ISSUE THREAD

**Issue by dilumn** [PassCloud/passcloud#1]
@asankad7 The purpose of PASSCloud is to create a Pass Framework to host Ruby on Rails applications easily to cloud. Can you go through some research on Pass & what is the purpose of it in cloud?

**Comment by AsankaD7** [comment]
@dilumn yep, but I don't know Ruby. I will found pass Framework  information and what is the purpose of it ok.

**Comment by dilumn** [comment]
I'll do the Ruby part in this project, but still I also don't have a clear idea about architecture of pass framework. Apache Statos is one of the examples that developed by WSO2 & this PassCloud also should function like Apache Statos but only with Ruby on Rails projects. Apache Statos can be extendable for any language, but it's hard. For now let's only focus on Ruby on Rails applications.

**Comment by AsankaD7** [comment]
ok
